clc 
clear all

load pattern.mat  % data generated by simulation of spatial PDE system
W1=[];H1=[];W_data=[];
for i=1:3001
X=squeeze(A(:,i,:));
k = 1;
[W, H] = nnmf(X, k);   %matrix factorization
W_data=[W_data,W];    % NMF reduced data
W_mean=mean(W,[1 2]);
W1=[W1;W_mean];   %mean of NMF reduced data
end
